spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybills
    password: postgres
    username: postgres

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    show-sql: true



springdoc:
  show-actuator: true
  title: MyBills
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
    tagsSorter: alpha
    doc-expansion: none