CREATE TABLE tb_usuario (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome_completo VARCHAR(255),
   apelido VARCHAR(255),
   email VARCHAR(255),
   senha VARCHAR(255),
   CONSTRAINT pk_tb_usuario PRIMARY KEY (id)
);